version: 2
updates:
  # Python dependencies for Jesse Core
  - package-ecosystem: "pip"
    directory: "/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "core-team"
    assignees:
      - "maintainer"
    labels:
      - "dependencies"
      - "core"
      - "auto-merge"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      # 忽略主要版本更新，需要手動審查
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "06:00"
    open-pull-requests-limit: 2
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-merge"
    commit-message:
      prefix: "ci"
      include: "scope"