coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
        
    patch:
      default:
        target: 80%
        threshold: 5%
        
  ignore:
    - "tests/"
    - "docs/"
    - "scripts/"
    - ".taskmaster/"
    - ".cursor/"
    - "contracts/lib/"
    - "contracts/cache/"
    - "**/__pycache__/"
    
flags:
  quality:
    paths:
      - core/jesse/
  functional:
    paths:
      - core/jesse/
      - jesse-defi-mev/
  hft:
    paths:
      - core/jesse/services/hft_*.py
      - core/jesse/indicators/hft_*.py
      - core/jesse/store/hft_*.py
  defi:
    paths:
      - jesse-defi-mev/
  contracts:
    paths:
      - contracts/src/
      
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true 