services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: jesse_db
      POSTGRES_USER: jesse_user
      POSTGRES_PASSWORD: jessepwd123
    ports:
      - "5434:5432" # Use port 5434 to avoid WSL conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6381:6379" # Use port 6381 to avoid conflicts
    restart: unless-stopped

volumes:
  postgres_data:
