name: Simple Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello from GitHub Actions!"
          echo "Current directory: $(pwd)"
          echo "Date: $(date)"
          echo "System info: $(uname -a)"
      
      - name: Check Python
        run: |
          which python3
          python3 --version
          echo "Python works!"